# Generated by Django 6.0.1 on 2026-03-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sharelink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'share_link',
            },
        ),
    ]
