# Generated by Django 6.0.1 on 2026-03-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('occasion', models.CharField(choices=[('birthday', 'birthday'), ('wedding', 'wedding'), ('anniversary', 'anniversary'), ('holiday', 'holiday'), ('other', 'other')], default='other', max_length=20)),
                ('genre', models.CharField(choices=[('pop', 'pop'), ('rock', 'rock'), ('jazz', 'jazz'), ('classical', 'classical'), ('hiphop', 'hiphop'), ('rb', 'rb'), ('folk', 'folk')], default='pop', max_length=10)),
                ('voice_type', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('instrumental', 'instrumental')], default='male', max_length=13)),
                ('mood', models.CharField(choices=[('happy', 'happy'), ('sad', 'sad'), ('romantic', 'romantic'), ('calm', 'calm'), ('funny', 'funny')], default='happy', max_length=10)),
                ('status', models.CharField(choices=[('generating', 'generating'), ('completed', 'completed'), ('failed', 'failed')], default='generating', max_length=11)),
                ('audiofile_url', models.CharField(max_length=500)),
                ('is_private', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'song',
            },
        ),
    ]
