# Generated by Django 6.0.1 on 2026-03-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audiofile_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
