# Generated by Django 6.0.3 on 2026-04-08 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_alter_song_audiofile_url'),
        ('songgenerationrequest', '0002_remove_songgenerationrequest_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='songgenerationrequest',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='song', to='songgenerationrequest.songgenerationrequest'),
        ),
    ]
