# Generated by Django 6.0.3 on 2026-04-08 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_song_songgenerationrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='songgenerationrequest',
            new_name='song_generation_request',
        ),
    ]
