# Generated by Django 6.0.3 on 2026-04-18 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_rename_songgenerationrequest_song_song_generation_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='status',
        ),
    ]
