# Generated by Django 6.0.3 on 2026-04-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songgenerationrequest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songgenerationrequest',
            name='song',
        ),
    ]
