# Generated by Django 6.0.3 on 2026-04-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songgenerationrequest', '0002_remove_songgenerationrequest_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='songgenerationrequest',
            name='taskId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
